### ISSUE TITLE
Error for sentences without the full stop

### ISSUE THREAD

**Issue by cansadadeserfeliz** [jerojasro/severoladrillo#2]
It also breaks with `\n` symbols.

![selection_853](https://user-images.githubusercontent.com/2270752/27183176-5f3935fe-51a3-11e7-9b7e-a4a1e1e245e6.png)

**Comment by jerojasro** [comment]
This is actually caused because of a bug in the code that detects proper nouns. Fixed in 84888adac43af989a0cff4b761d7d69eca2e849f

**Comment by jerojasro** [comment]
also, for text with `\n` symbols, there is already a bug to add support for that: https://github.com/jerojasro/severoladrillo/issues/1
